### PR TITLE
gcati-953-1085-zombie, ensure that the enums serving the joins are id…

### PR DESCRIPTION
**Pull request by decet**
Hello all. 

gcati-953-1085-zombie, ensure that the enums serving the join in a test are identical.

Obsolete test_id/event_id enums will be removed, after data cleansing/DB bifurcation.
We don't expect to support the old event_ids/test_ids, but I'd like to get this particular task completed, so
Jerry's tests will go green on the join between ftr_metdata and file_metadata.

There is a superfluous change added as well. In 3 of the descriptions, a tab was used to indent, 
and my editor has removed it and replaced it with the proper number of spaces.

### CODE REVIEW

**Review by drsmit22 — APPROVED** [review]
Assuming we are keeping the old and the new enum values (newer ones starting with NC1-), this looks right.

**Comment by tbagnallMATM** [comment]
A conversation would probably be easiest for sorting this out, but until then...

In an ideal world, we would have something like below:

- NC1-DT1-X3
- NC1-DT1-X4
- NC1-DT1-VIRTUAL-DRY-RUN
- NC1-DT1-FAM1
- NC1-DT1-BuildupRun1
- NC1-DT1-BuildupRun2-Preconnectivity1
- NC1-DT1-BuildupRun2-Preconnectivity2
- NC1-DT1-BuildupRun2 
- NC1-DT1-BuildupRun3


But I think the cat is out of the bag for X3, X4, and VIRTUAL_DRY_RUN, correct? At least when I search for distinct fields in dss.ftr_metadata 'X3,' 'X4,' and 'VIRTUAL_DRY_RUN' already exist. If so, and we cannot change these, then I think the next best solution is: 

- X3
- X4
- VIRTUAL_DRY_RUN
- NC1-DT1-FAM1
- NC1-DT1-BuildupRun1
- NC1-DT1-BuildupRun2-Preconnectivity1
- NC1-DT1-BuildupRun2-Preconnectivity2
- NC1-DT1-BuildupRun2 
- NC1-DT1-BuildupRun3

This removes the following enums which are taken care of above:

 - BUILDUP_RUN_1 (Covered by NC1-DT1-BuildupRun1)
 - BUILDUP_RUN_2 (Covered by NC1-DT1-BuildupRun2)
 - BUILDUP_RUN_3 (Covered by NC1-DT1-BuildupRun2)
 - DT (Covered implicitly)

**Comment by decet** [comment]
Thanks, Tim. I'm think I'm heading toward a less "merged" solution that I think might be simpler. Let me know if this sounds satisfactory:

My intention is to:
1) add the old fields to both of the swagger models that they need to be in.
2) seek an affirmation that I have addressed the problem with the join between file metadata and ftr metadata.
3) bifurcate/split the new DT1 database from the fully matured X3 database (selecting only some data).
4) remove the old enums from both tables

Restating:

As you said, the cat is out of the bag for the current database: There are values of X3, VIRTUAL_DRY_RUN in the database already, and my version migrations have to respect that.

My expectation is that although these old values will be present in the database, we will not be adding new data that uses them. After bifurcation, the old, relict values will be left behind, and I can afford to just drop the old data in the new DB, and to drop the old enum values from the two models in one dark frenzy. 

The bifurcation, which is the sundering, the separation, the splitting of the X3-containing database from the next event, DT1, is an important consideration in this approach. Without the imminent bifurcation, I think we would be doing something like you suggest.

Right now, I'm just doing the least I can to get Jerry's tests to go green, and I believe this is the fastest with the fewest renegotiations of naming standards.

**Comment by tbagnallMATM** [comment]
Sounds good, thank you, Dan.

**Comment by jwilwerding** [comment]
As things stand, the java integration tests are still broken. The issue is what value of event/test id should the integration tests use now and long term. The code is currently using 
EventIdEnum.BUILDUPRUN1 which translates into NC1-DT1-BuildupRun1
I believe this is a valid long term enumeration.
This value exists in the EventIdEnum of FileMetadata. The value does NOT exist in TestIdEnum of FlightRunMetadata.

Solutions: 
1) Make sure TestIdEnum has the proper long term event enumerations which also implies the db constraints match.
2) Change the integration tests to use the deprecated "BUIDUP_RUN_1" value. This implies tests will break whenever the old values are removed.

My preference is the first, but I'll go along with the consensus as I just want the builds to work again.

If anyone wants to run the tests manually, from the aerograph/aerograph-rest folder, execute "./buildAll.sh int"
This command will generate all swagger code required by etl/aerograph, build all of the etl code (excluding aws components) and also execute the integration tests. You will need to have a current, local database for the integration tests to insert/retrieve content.
A similar script lives under etl if you don't care about aerograph-rest.

**Comment by decet** [comment]
Jerry, I believe this change to the OpenAPI files addresses this issue. I'll run the tests you suggest before I merge.

After I merge these swagger files, the values for the enum in event_id in FileMetadata will be identical to the values for the enum in FlightRunMetadata (as they are called in the yaml files):

             - X3
              - X4
              - VIRTUAL_DRY_RUN
              - BUILDUP_RUN_1
              - BUILDUP_RUN_2
              - BUILDUP_RUN_3
              - DT
              - NC1-DT1-FAM1
              - NC1-DT1-BuildupRun1
              - NC1-DT1-BuildupRun2-Preconnectivity1
              - NC1-DT1-BuildupRun2-Preconnectivity2
              - NC1-DT1-BuildupRun2
              - NC1-DT1-BuildupRun3

Again, we are not going to continue using the deprecated values for these two fields. I am retaining the obsolete versions transitionally, while I am halfway between two databases, one of which contains rows that have these obsolete values in them, and the other of which, the newer one, will not.

**Comment by decet** [comment]
Tested in part of Jerry's environment and gotten and gotten his endorsement of the changes.

**Comment by decet** [comment]
Wrong button.

**Pull request merged**
