### PR TITLE
GCATI-1729 valid per openapi3 document combining endpoints, security …

### PR DESCRIPTION
**Pull request by issmith1**
…and models

### CODE REVIEW

**Comment by decet** [comment]
I'd like to see the model and the API paths separated. It's a demonstrated capability in the data pipeline, and allows better modularity: changes to the model are visibly distinct from changes to the API, and changes to one don't induce changes to the other.

**Comment by decet** [comment]
Go ahead and remove the data model from the API: it's now redundant. I've submitted a pull request for the data model domain. The API can remain in this pull request on github so we don't overlap.

**Comment by issmith1** [comment]
not sure what is going on . 

The requireemnts are, 
customer can copy paste one set of text and view in an openapi viewer. 
customer can create Diff URLs
for Description text, customer can view the data such that it is clear which Description corresponds to whihc element

the industry common practice is one file.

**Review by meshow — APPROVED** [review]

**Comment by decet** [comment]
PUT endpoint for Producer appears to be wrong: does not reference the ProducerObject.
Just verified with swaggerhub: definitely missing the reference to the ProducerObject

**Comment by decet** [comment]
As agreed during scrum, no need to separate API from model domain: more convenient for targeted customer.

**Pull request merged**
